# Generated by Django 2.2.6 on 2019-10-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='desciption',
            new_name='description',
        ),
    ]
